AWSTemplateFormatVersion: "2010-09-09"
Description: 'Cloudformation stack that launches a single instance running the Drupal stack on Ubuntu 22.04'
Parameters:
  SandboxVPC:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC to use for SecurityGroup'
  SQLRootPass:
    Type: String
    Description: 'Root password for MariaDB installation'
    NoEcho: 'true'
    MinLength: '11'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must only contain upper and lowercase letters, numbers and contain a minimum of 11 characters
  DrupalDBName:
    Type: String
    Description: 'Drupal database name'
    Default: drupal
  DrupalDBUser:
    Type: String
    Description: 'Drupal username'
    Default: 'drupaluser'
  DrupalDBPass:
    Type: String
    Description: 'Drupal database password'
    NoEcho: 'true'
    MinLength: '11'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must only contain upper and lowercase letters, numbers and contain a minimum of 11 characters
  InstanceType:
    Type: String
    Description: 'EC2 instance type (family and size) to launch Drupal on'
    AllowedValues:
    - t3.nano
    - t3.micro
    - t3.small
    - t3.medium
    - m5.medium
    - m5.large
    ConstraintDescription: 'Must be a valid EC2 instance type.'
    Default: t3.small
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'SSH keypair name for access to EC2 instance'
    ConstraintDescription: 'Must be a valid SSH keypair'
  SandboxSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: 'Subnet to launch the instance into'
  InstanceName:
    Type: String
    Description: 'Tag name for the Drupal EC2 instance'
    Default: ec2-drupal-singleinstance
    
Mappings:
  AWSInstanceType2Arch:
    m5.large:
      Arch: HVM64
    m5.medium:
      Arch: HVM64
    t3.medium:
      Arch: HVM64
    t3.micro:
      Arch: HVM64
    t3.nano:
      Arch: HVM64
    t3.small:
      Arch: HVM64
  AWSInstanceType2NATArch:
    m5.medium:
      Arch: NATHVM64
    m5.large:
      Arch: NATHVM64
    t3.medium:
      Arch: NATHVM64
    t3.micro:
      Arch: NATHVM64
    t3.nano:
      Arch: NATHVM64
    t3.small:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0557a15b87f6559cf
      HVMG2: ami-e998ea83
      PV64: ami-5fb8c835
    us-east-2:
      HVM64: ami-00eeedc4036573771
      # HVMG2: 
      # PV64: 
    us-west-1:
      HVM64: ami-07bc04fdc13241142
      HVMG2: ami-943956f4
      PV64: ami-56ea8636
    us-west-2:
      HVM64: ami-0735c191cf914754d
      HVMG2: ami-315f4850
      PV64: ami-d93622b8

Resources:
  DrupalSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22 and 80
      VpcId: !Ref SandboxVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0

  DrupalInstance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          drupal_setup:
            - config_cfn
            - install_packages
            - mysql_secure_installation
            - install_drupal
            - config_drupal
        config_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
                verbose=true
              mode: '000400'
              owner: 'root'
              group: 'root'
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.DrupalInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource DrupalInstance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: 'root'
              group: 'root'
            /lib/systemd/system/cfn-hup.service:
              content: !Sub |
                [Unit]
                Description=cfn-hup daemon
                [Service]
                Type=simple
                ExecStart=/usr/local/bin/cfn-hup
                Restart=always
                [Install]
                WantedBy=multi-user.target
          commands:
            01enable_cfn_hup:
              command: systemctl enable cfn-hup.service
            02start_cfn_hup:
              command: systemctl start cfn-hup.service
        install_packages:
          commands:
            01_install_packages:
              command: "apt install apache2 mariadb-server-10.6 mariadb-client-10.6 -y"
            02_remove_indexhtml:
              command: "rm -rf /var/www/html/index.html"
            03_install_php:
              command: "apt install php8.1 php-dom php-gd php-simplexml php-xml php-opcache php-mbstring php-mysql -y"
            04_allow_override:
              command: "sed -i '0,/AllowOverride\ None/! {0,/AllowOverride\ None/ s/AllowOverride\ None/AllowOverride\ All/}' /etc/apache2/apache2.conf"
            05_mod_rewrite:
              command: "a2enmod rewrite"
            05_enable_httpd:
              command: "systemctl enable apache2 && systemctl start apache2"
            06_enable_mariadb:
              command: "systemctl enable mariadb && systemctl start mariadb"
        mysql_secure_installation:
          files:
            /tmp/secure-install:
              content: !Sub |
                #!/bin/bash -xe
                mysql -sfu root <<EOS
                -- set root password
                ALTER USER 'root'@'localhost' IDENTIFIED VIA mysql_native_password;
                SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${SQLRootPass}');
                -- delete anonymous users
                DELETE FROM mysql.user WHERE User='';
                -- delete remote root capabilities
                DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
                -- drop database 'test'
                DROP DATABASE IF EXISTS test;
                -- also make sure there are lingering permissions to it
                DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
                -- make changes immediately
                FLUSH PRIVILEGES;
                EOS
              mode: '000500'
              owner: root
              group: root
            /tmp/my-cnf:
              content: !Sub |
                #!/bin/bash -xe
                touch /root/.my.cnf
                chmod 700 /root/.my.cnf
                echo "[client]">>/root/.my.cnf
                echo "user=root">>/root/.my.cnf
                echo "password=${SQLRootPass}">>/root/.my.cnf
              mode: '000500'
              owner: root
              group: root
          commands:
            01_secure_install:
              cwd: /tmp/
              command: /tmp/secure-install
            02_my_cnf:
              cwd: /tmp/
              command: /tmp/my-cnf
        install_drupal:
          commands:
            01_download_drupal:
              cwd: /tmp/
              command: "wget https://www.drupal.org/download-latest/tar.gz"
            02_extract_drupal:
              cwd: /tmp/
              command: "tar -C /var/www/html/ -zxf tar.gz --strip-components=1"
            03_chmod_drupal:
              cwd: /var/www/html/
              command: "chown -R www-data:www-data /var/www/html/"
        config_drupal:
          files:
            /tmp/drupal-config:
              content: !Sub |
                #!/bin/bash -xe
                mysql -u root --password='${SQLRootPass}' -e "CREATE DATABASE ${DrupalDBName};"
                mysql -u root --password='${SQLRootPass}' -e "CREATE USER '${DrupalDBUser}'@'localhost' IDENTIFIED BY '${DrupalDBPass}';"
                mysql -u root --password='${SQLRootPass}' -e "GRANT ALL PRIVILEGES ON ${DrupalDBName}.* TO '${DrupalDBUser}'@'localhost';"
                mysql -u root --password='${SQLRootPass}' -e "FLUSH PRIVILEGES;"
              mode: '000500'
              owner: root
              group: root
          commands:
            01_drupal_config:
              cwd: /tmp/
              command: /tmp/drupal-config
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
      KeyName: !Ref SSHKey
      SecurityGroupIds: 
        - !Ref DrupalSecurityGroup
      SubnetId: !Ref SandboxSubnet
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          apt update -y && apt upgrade -y
          apt-get -y install python3-pip
          mkdir -p /opt/aws/
          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          ln -s /usr/local/init/ubuntu/cfn-hup /etc/init.d/cfn-hup
          /usr/local/bin/cfn-init -v --stack ${AWS::StackId} --resource DrupalInstance --configsets drupal_setup --region ${AWS::Region}
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource DrupalInstance --region ${AWS::Region}

Outputs:
  WebsiteURL:
    Description: Drupal Website
    Value: !Sub "http://${DrupalInstance.PublicDnsName}"