AWSTemplateFormatVersion: "2010-09-09"
Description: 'Cloudformation stack that launches a single instance running the Wordpress stack on Red Hat Enterprise Linux 9'
Parameters:
  WordpressVPC:
    Type: AWS::EC2::VPC::Id
    Description: 'VPC to use for SecurityGroup'
  SQLRootPass:
    Type: String
    Description: 'Root password for MariaDB installation'
    NoEcho: 'true'
    MinLength: '11'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must only contain upper and lowercase letters, numbers and contain a minimum of 11 characters
  WPDBName:
    Type: String
    Description: 'Wordpress database name'
    Default: wordpress
  WPDBUser:
    Type: String
    Description: 'Wordpress username'
    Default: 'wpuser'
  WPDBPass:
    Type: String
    Description: 'Wordpress database password'
    NoEcho: 'true'
    MinLength: '11'
    AllowedPattern: "[a-zA-Z0-9]*"
    ConstraintDescription: Must only contain upper and lowercase letters, numbers and contain a minimum of 11 characters
  InstanceType:
    Type: String
    Description: 'EC2 instance type (family and size) to launch Wordpress on'
    AllowedValues:
    - t3.micro
    - t3.small
    - t3.medium
    - t3.large
    - m5.medium
    - m5.large
    ConstraintDescription: 'Must be a valid EC2 instance type.'
    Default: t3.small
  SSHKey:
    Type: AWS::EC2::KeyPair::KeyName
    Description: 'SSH keypair name for access to EC2 instance'
    ConstraintDescription: 'Must be a valid SSH keypair'
  WordpressSubnet:
    Type: AWS::EC2::Subnet::Id
    Description: 'Subnet to launch the instance into'
  InstanceName:
    Type: String
    Description: 'Tag name for the WordPress EC2 instance'
    Default: ec2-wordpress-singleinstance
    
Mappings:
  AWSInstanceType2Arch:
    m5.large:
      Arch: HVM64
    m5.medium:
      Arch: HVM64
    t3.medium:
      Arch: HVM64
    t3.micro:
      Arch: HVM64
    t3.nano:
      Arch: HVM64
    t3.small:
      Arch: HVM64
  AWSInstanceType2NATArch:
    m5.medium:
      Arch: NATHVM64
    m5.large:
      Arch: NATHVM64
    t3.medium:
      Arch: NATHVM64
    t3.micro:
      Arch: NATHVM64
    t3.nano:
      Arch: NATHVM64
    t3.small:
      Arch: NATHVM64
  AWSRegionArch2AMI:
    us-east-1:
      HVM64: ami-0c9978668f8d55984
      HVMG2: ami-e998ea83
      PV64: ami-5fb8c835
    us-east-2:
      HVM64: ami-0521a1ab6cb98215d
      # HVMG2: 
      # PV64: 
    us-west-1:
      HVM64: ami-02c61cf220bd1158e
      HVMG2: ami-943956f4
      PV64: ami-56ea8636
    us-west-2:
      HVM64: ami-0edab8d70528476d3
      HVMG2: ami-315f4850
      PV64: ami-d93622b8

Resources:
  WPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Open Ports 22 and 80
      VpcId: !Ref WordpressVPC
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: '22'
        ToPort: '22'
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: '80'
        ToPort: '80'
        CidrIp: 0.0.0.0/0

  WPInstance:
    Type: 'AWS::EC2::Instance'
    Metadata:
      'AWS::CloudFormation::Init':
        configSets:
          wp_setup:
            - config_cfn
            - install_packages
            - mysql_secure_installation
            - install_wordpress
            - config_wordpress
            - wordpress_salts
        config_cfn:
          files:
            /etc/cfn/cfn-hup.conf:
              content: !Sub |
                [main]
                stack=${AWS::StackName}
                region=${AWS::Region}
                interval=1
                verbose=true
              mode: '000400'
              owner: 'root'
              group: 'root'
            /etc/cfn/hooks.d/cfn-auto-reloader.conf:
              content: !Sub |
                [cfn-auto-reloader-hook]
                triggers=post.update
                path=Resources.WPInstance.Metadata.AWS::CloudFormation::Init
                action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackId} --resource WPInstance --region ${AWS::Region}
                runas=root
              mode: '000400'
              owner: 'root'
              group: 'root'
            /lib/systemd/system/cfn-hup.service:
              content: !Sub |
                [Unit]
                Description=cfn-hup daemon
                [Service]
                Type=simple
                ExecStart=/usr/local/bin/cfn-hup
                Restart=always
                [Install]
                WantedBy=multi-user.target
              mode: '000400'
              owner: 'root'
              group: 'root'
          commands:
            01enable_cfn_hup:
              command: systemctl enable cfn-hup.service
            02start_cfn_hup:
              command: systemctl start cfn-hup.service
        install_packages:
          commands:
            01_install_packages:
              command: "dnf install lynx wget httpd mariadb mariadb-server -y"
            02_install_php:
              command: "dnf module reset php && dnf module enable php:8.1 -y && dnf install php -y && dnf install php-bz2 php-mysqli php-curl php-gd php-intl php-common php-mbstring php-xml -y"
            03_enable_httpd:
              command: "systemctl enable httpd && systemctl start httpd"
            04_enable_mariadb:
              command: "systemctl enable mariadb && systemctl start mariadb"
        mysql_secure_installation:
          files:
            /tmp/secure-install:
              content: !Sub |
                #!/bin/bash -xe
                mysql -sfu root <<EOS
                -- set root password
                ALTER USER 'root'@'localhost' IDENTIFIED VIA mysql_native_password;
                SET PASSWORD FOR 'root'@'localhost' = PASSWORD('${SQLRootPass}');
                -- delete anonymous users
                DELETE FROM mysql.user WHERE User='';
                -- delete remote root capabilities
                DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');
                -- drop database 'test'
                DROP DATABASE IF EXISTS test;
                -- also make sure there are lingering permissions to it
                DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';
                -- make changes immediately
                FLUSH PRIVILEGES;
                EOS
              mode: '000500'
              owner: root
              group: root
            /tmp/my-cnf:
              content: !Sub |
                #!/bin/bash -xe
                touch /root/.my.cnf
                chmod 700 /root/.my.cnf
                echo "[client]">>/root/.my.cnf
                echo "user=root">>/root/.my.cnf
                echo "password=${SQLRootPass}">>/root/.my.cnf
              mode: '000500'
              owner: root
              group: root
          commands:
            01_secure_install:
              cwd: /tmp/
              command: /tmp/secure-install
            02_my_cnf:
              cwd: /tmp/
              command: /tmp/my-cnf
        install_wordpress:
          commands:
            01_download_wordpress:
              cwd: /tmp/
              command: "wget http://wordpress.org/latest.tar.gz"
            02_extract_wordpress:
              cwd: /tmp/
              command: "tar -C /var/www/html/ -zxf latest.tar.gz --strip-components=1"
            03_chmod_wordpress:
              cwd: /var/www/html/
              command: "chown -R apache:apache /var/www/html/"
        config_wordpress:
          files:
            /tmp/create-wp-config:
              content: !Sub |
                #!/bin/bash -xe
                mv /var/www/html/wp-config-sample.php /var/www/html/wp-config.php
                sed -i "s/'database_name_here'/'${WPDBName}'/g" /var/www/html/wp-config.php
                sed -i "s/'username_here'/'${WPDBUser}'/g" /var/www/html/wp-config.php
                sed -i "s/'password_here'/'${WPDBPass}'/g" /var/www/html/wp-config.php
              mode: '000500'
              owner: root
              group: root
            /tmp/create-htaccess:
              content: !Sub |
                #!/bin/bash -xe
                cat << EOF >> /var/www/html/.htaccess
                # BEGIN WordPress
                <IfModule mod_rewrite.c>
                RewriteEngine On
                RewriteBase /
                RewriteRule ^index.php$ - [L]
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteRule . /index.php [L]
                </IfModule>
                # END WordPress
                EOF
              mode: '000500'
              owner: root
              group: root
          commands:
            01_create_wp_config:
              cwd: /tmp/
              command: /tmp/create-wp-config
            02_create_ht_access:
              cwd: /tmp/
              command: /tmp/create-htaccess
        wordpress_salts:
          files:
            /tmp/wordpress-salts:
              content: !Sub |
                #!/bin/bash -xe
                grep -A50 'table_prefix' /var/www/html/wp-config.php > /tmp/wp-tmp-config
                sed -i '/**#@/,/$p/d' /var/www/html/wp-config.php
                lynx --dump -width 200 https://api.wordpress.org/secret-key/1.1/salt/ >> /var/www/html/wp-config.php
                cat /tmp/wp-tmp-config >> /var/www/html/wp-config.php && rm /tmp/wp-tmp-config -f
                mysql -u root --password='${SQLRootPass}' -e "CREATE DATABASE ${WPDBName};"
                mysql -u root --password='${SQLRootPass}' -e "CREATE USER '${WPDBUser}'@'localhost' IDENTIFIED BY '${WPDBPass}';"
                mysql -u root --password='${SQLRootPass}' -e "GRANT ALL PRIVILEGES ON ${WPDBName}.* TO '${WPDBUser}'@'localhost';"
                mysql -u root --password='${SQLRootPass}' -e "FLUSH PRIVILEGES;"
              mode: '000500'
              owner: root
              group: root
          commands:
            01_wordpress_salts:
              cwd: /tmp/
              command: /tmp/wordpress-salts
    CreationPolicy:
      ResourceSignal:
        Timeout: PT15M
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !FindInMap [AWSRegionArch2AMI, !Ref 'AWS::Region', !FindInMap [AWSInstanceType2Arch, !Ref InstanceType, Arch]]
      KeyName: !Ref SSHKey
      SecurityGroupIds: 
        - !Ref WPSecurityGroup
      SubnetId: !Ref WordpressSubnet
      Tags:
        - Key: Name
          Value: !Ref InstanceName
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash -xe
          dnf update -y
          yum -y install python3-pip
          pip3 install https://s3.amazonaws.com/cloudformation-examples/aws-cfn-bootstrap-py3-latest.tar.gz
          /usr/local/bin/cfn-init -v --stack ${AWS::StackId} --resource WPInstance --configsets wp_setup --region ${AWS::Region}
          /usr/local/bin/cfn-signal -e $? --stack ${AWS::StackId} --resource WPInstance --region ${AWS::Region}

Outputs:
  WebsiteURL:
    Description: WordPress Website
    Value: !Sub "http://${WPInstance.PublicDnsName}"