AWSTemplateFormatVersion: "2010-09-09"
Description: Simple stack that introduces mappings
Mappings: # Amazon Linux 2 AMI in each region (updated from initial course config)
  RegionMap: # Updated from initial course config, added us-east-2 and us-west-2, removed EU and AP regions
    us-east-1:
      AMI: ami-0323c3dd2da7fb37d
    us-east-2:
      AMI: ami-0f7919c33c90f5b58
    us-west-1:
      AMI: ami-06fcc1f0bc2c8943f
    us-west-2:
      AMI: ami-0d6621c01e8c2de2c
  # Enable the use of an input value, to determine another value
  # Determine your AMI ID based on the region you're launching your stack in
  # First parameter is the map name, second is your top level key, and last your second level key
  # !FindInMap [MapName, TopLevelKey, SecondLevelKey]
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap # Map Name
        - !Ref AWS::Region # Top Level Key (a pseudo parameter in this case)
        - AMI # Second Level Key
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: !Join 
            - ""
            - - "EC2 Instance for "
              - !Ref AWS::Region
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0