AWSTemplateFormatVersion: "2010-09-09"
Description: Simple stack that introduces input parameters
Parameters:
  NameOfService:
    Description: "The name of the service this stack is to be used for."
    Type: String
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access into the server
    Type: AWS::EC2::KeyPair::KeyName
# Supported parameter types;
# String
# Number
# List<Number>
# CommaDelimitedList
# AWS-specific types (AWS::EC2::Image::Id)
# Systems Manager Parameter types
# Parameters are then called in the resources section using Ref
Mappings: # Amazon Linux 2 AMI in each region (updated from initial course config)
  RegionMap: # Updated from initial course config, added us-east-2 and us-west-2, removed EU and AP regions
    us-east-1:
      AMI: ami-0323c3dd2da7fb37d
    us-east-2:
      AMI: ami-0f7919c33c90f5b58
    us-west-1:
      AMI: ami-06fcc1f0bc2c8943f
    us-west-2:
      AMI: ami-0d6621c01e8c2de2c
Resources:
  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags:
        - Key: "Name"
          Value: !Ref NameOfService
      KeyName: !Ref KeyName
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0