Resources:
  ImgBldrDemoImagePipeline:
    Type: 'AWS::ImageBuilder::ImagePipeline'
    Properties:
      Name: 'Image Builder Demo Image Pipeline'
      Description: 'Demo image pipeline for Amazon Linux 2 Image created with EC2 Image Builder and CloudFormation'
      ImageRecipeArn: {Insert image recipe ARN here}
      InfrastructureConfigurationArn: {Insert image }
      ImageTestsConfiguration:
        ImageTestsEnabled: false
        TimeoutMinutes: 90
      Status: 'ENABLED'