Resources:
  ImgBldrDemoDistributionConfiguration:
    Type: 'AWS::ImageBuilder::DistributionConfiguration'
    Properties:
      Name: 'imgbldr-demo-distroConfig'
      Description: 'Image Builder demo distribution configuration'
      Distributions:
        - Region: 'us-east-1'
          AmiDistributionConfiguration:
            Name: 'demo-imgBldr-ami {{ imagebuilder:buildDate }}'
            AmiTags:
              AmiTagKey: 'imgBldr-demo-test'
            LaunchPermissionConfiguration:
              UserIds:
                - '{insert AWS account number here}'