Resources:
  ImageBuilderDemoRecipe:
    Type: 'AWS::ImageBuilder::ImageRecipe'
    Properties:
      Name: 'Image Builder Demo Recipe'
      Version: '1.0.0'
      ParentImage: 'arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-2-x86/2020.9.4'
      Description: 'Test recipe for Amazon Linux 2 Gold Image created with CloudFormation for blog demo'
      Components:
        - ComponentArn: arn:aws:imagebuilder:us-east-1:aws:component/update-linux/1.0.0/1
        - ComponentArn: {insert component ARN here after creating}
        - ComponentArn: arn:aws:imagebuilder:us-east-1:aws:component/stig-build-linux-medium/2.6.0/1