AWSTemplateFormatVersion: '2010-09-09'
Description: Account Creation Stack
Parameters:
  ModuleName: # Name of the Lambda Module
    Description: The name of the Python file
    Type: String
    Default: "createAccount"
  S3Bucket:
    Description: The name of the bucket that contains your packaged source
    Type: String
    Default: "create-account"
  S3Key: # Name of the zip file
    Description: The name of the ZIP package
    Type: String
    Default: "createAccount.zip"
  AccountName:
    Description: Account Name To Be Created
    Type: String
    Default: "crOrganizationTest"
  OUName:
    Description: Organizational Unit Name To Be Created
    Type: String
    Default: "crTestingOU"
  Email:
    Description: Email Address used for the Account
    Type: String
  ParentOUID:
    Description: Parent Organizational Unit (OU) ID to launch this new account into
    Type: String
  RootOUID:
    Description: Root Organizational Unit (OU) to launch this new account into
    Type: String
Resources:
  CreateAccount:
    Type: Custom::CreateAccount
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - TestFunction
        - Arn
      AccountName:
        Ref: AccountName
      OUName:
        Ref: OUName
      Email:
        Ref: Email
      ParentOUID:
        Ref: ParentOUID
      RootOUID:
        Ref: RootOUID
  TestFunction: # Lambda Function
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket:
          Ref: S3Bucket
        S3Key:
          Ref: S3Key
      Handler:
        Fn::Join:
        - ''
        - - Ref: ModuleName
          - ".lambda_handler"
      Role:
        Fn::GetAtt:
        - LambdaExecutionRole
        - Arn
      Runtime: python2.7
      Timeout: '30'
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: root
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
      - PolicyName: Acct
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - organizations:*
            Resource: "*"
Outputs:
  Message:
    Description: Message returned from Lambda
    Value:
      Fn::GetAtt:
      - CreateAccount
      - Message
