AWSTemplateFormatVersion: '2010-09-09'
Description: |
  CloudFormation template that builds an EKS stack including IAM roles  and policy, the 
  EKS cluster, and an EKS node group. This stack launches three nested stacks; one that 
  builds the IAM roles and policy, one that builds and manages the EKS cluster, and the 
  last builds and manages the EKS node group.
Parameters:
  EksStackVpc:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID to use for the EKS cluster, the LB policy needs to reference this VPC
    Default: vpc-074dd12a38bf41e3d
  EksClusterName:
    Type: String
    Description: Desired name for the EKS cluster
    Default: cssg-eks-cluster
  EksVpcSecurityGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group to attach to the Cluster to allow VPC communication
    Default: sg-00c3f1b5d006d3d51
  EksSubnet1:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet 1 ID to use for the EKS cluster
    Default: subnet-03b818ccec4003ef8
  EksSubnet2:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet 2 ID to use for the EKS cluster
    Default: subnet-063ae1c5ace129151
  IamStackLBPolicyName:
    Type: String
    Description: Name for the EKS Loadbalancing policy name
    Default: cssg-loadBalancing
  IamStackIngressPolicyName:
    Type: String
    Description: Name for the EKS Ingress Controller policy name
    Default: cssg-albIngressControllerPolicy
  IamStackClusterRoleName:
    Type: String
    Description: Name for the EKS Cluster role
    Default: cssg-eks-role
  IamStackNodeGroupRoleName:
    Type: String
    Description: Name for the EKS Node Group role
    Default: cssg-nodeGroup-role
  IamStackAmazonEKSClusterPolicy:
    Type: String
    Description: ARN of the AmazonEKSClusterPolicy to add to EKS Cluster role
    Default: arn:aws:iam::aws:policy/AmazonEKSClusterPolicy
  IamStackAmazonEKSWorkerNodePolicy:
    Type: String
    Description: ARN of the AmazonEKSWorkerNodePolicy to add to EKS Cluster role
    Default: arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
  IamStackAmazonEKSServicePolicy:
    Type: String
    Description: ARN of the AmazonEKSServicePolicy to add to EKS Cluster role
    Default: arn:aws:iam::aws:policy/AmazonEKSServicePolicy
  IamStackAmazonEKSCNIPolicy:
    Type: String
    Description: ARN of the AmazonEKS_CNI_Policy to add to EKS Cluster role
    Default: arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
  IamStackAmazonEC2ContainerRegistryReadOnly:
    Type: String
    Description: ARN of the AmazonEC2ContainerRegistryReadOnly to add to EKS Cluster role
    Default: arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
  NodeGroupStackKeyName:
    Description: The EC2 key pair to allow ssh access to the instances
    Type: AWS::EC2::KeyPair::KeyName
    Default: acsg-linux
  NodeGroupStackNodeAmiType:
    Type: String
    Description: AMI type to be used for your cluster nodes
    Default: AL2_x86_64
    AllowedValues:
    - AL2_x86_64
    - AL2_x86_64_GPU
    - AL2_ARM_64
  NodeGroupStackNodeInstanceType:
    Description: EC2 instance type for the node instances
    Type: String
    Default: t3.medium
    AllowedValues:
    - t3.small
    - t3.medium
    - t3.large
    - t3.xlarge
    - t3.2xlarge
    - m5.large
    - m5.xlarge
    - m5.2xlarge
    - m5.4xlarge
    - m5.12xlarge
    - m5.24xlarge
    - c5.large
    - c5.xlarge
    - c5.2xlarge
    - c5.4xlarge
    - c5.9xlarge
    - c5.18xlarge
    - i3.large
    - i3.xlarge
    - i3.2xlarge
    - i3.4xlarge
    - i3.8xlarge
    - i3.16xlarge
    - r4.large
    - r4.xlarge
    - r4.2xlarge
    - r4.4xlarge
    - r4.8xlarge
    - r4.16xlarge
    - x1.16xlarge
    - x1.32xlarge
    - p3.2xlarge
    - p3.8xlarge
    - p3.16xlarge
    ConstraintDescription: must be a valid EC2 instance type
  NodeGroupStackNodeGroupASGMin:
    Type: Number
    Description: Minimum number of EC2 instances to launch into the node group
    Default: 2
  NodeGroupStackNodeGroupASGDesired:
    Type: Number
    Description: Steady state number of EC2 instance that should be running in the node group
    Default: 2
  NodeGroupStackNodeGroupASGMax:
    Type: Number
    Description: Maximum number of instances that will launch in the node group
    Default: 4
  NodeGroupStackNodeGroupName:
    Type: String
    Description: Unique name of the node group
    Default: cssg-test-eksCluster-nodeGroup

Resources:
  EksIamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cssg-test-cloudformation-templates.s3.amazonaws.com/cssg-eks-iam.yaml'
      Parameters:
        LBPolicyName: !Ref IamStackLBPolicyName
        IngressPolicyName: !Ref IamStackIngressPolicyName
        EksVpc: !Ref EksStackVpc
        ClusterRoleName: !Ref IamStackClusterRoleName
        NodeGroupRoleName: !Ref IamStackNodeGroupRoleName
        AmazonEKSClusterPolicy: !Ref IamStackAmazonEKSClusterPolicy
        AmazonEKSWorkerNodePolicy: !Ref IamStackAmazonEKSWorkerNodePolicy
        AmazonEKSServicePolicy: !Ref IamStackAmazonEKSServicePolicy
        AmazonEKSCNIPolicy: !Ref IamStackAmazonEKSCNIPolicy
        AmazonEC2ContainerRegistryReadOnly: !Ref IamStackAmazonEC2ContainerRegistryReadOnly
  EksClusterStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cssg-test-cloudformation-templates.s3.amazonaws.com/cssg-eks-cluster.yaml'
      Parameters:
        EksVpc: !Ref EksStackVpc
        ClusterName: !Ref EksClusterName
        IAMRoleARN:
          Fn::GetAtt:
            - EksIamStack
            - Outputs.ClusterRoleArn
        VpcSecurityGroup: !Ref EksVpcSecurityGroup
        ClusterSubnet1: !Ref EksSubnet1
        ClusterSubnet2: !Ref EksSubnet2
  EksNodeGroupStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'https://cssg-test-cloudformation-templates.s3.amazonaws.com/cssg-eks-nodeGroup.yaml'
      Parameters:
        ClusterName: !Ref EksClusterName
        ClusterControlPlaneSecurityGroup:
          Fn::GetAtt:
            - EksClusterStack
            - Outputs.ClusterControlPlaneSecurityGroup
        KeyName: !Ref NodeGroupStackKeyName
        NodeRole:
          Fn::GetAtt:
            - EksIamStack
            - Outputs.NodeGroupRoleArn
        VpcSecurityGroup: !Ref EksVpcSecurityGroup
        EksVpc: !Ref EksStackVpc
        NodeAmiType: !Ref NodeGroupStackNodeAmiType
        NodeInstanceType: !Ref NodeGroupStackNodeInstanceType
        NodeGroupASGMin: !Ref NodeGroupStackNodeGroupASGMin
        NodeGroupASGDesired: !Ref NodeGroupStackNodeGroupASGDesired
        NodeGroupASGMax: !Ref NodeGroupStackNodeGroupASGMax
        ClusterSubnet1: !Ref EksSubnet1
        ClusterSubnet2: !Ref EksSubnet2
        NodeGroupName: !Ref NodeGroupStackNodeGroupName